version: "3.5"
services:
  backend:
    build: ./sportradar-code-challenge-backend
    ports:
      - 4200:4200
    environment:
      - PORT=4200
  front:
    build: ./sportradar-code-challenge-frontend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:4200
